function DispatchBlip(data)
    PlaySound(-1, 'Lose_1st', 'GTAO_FM_Events_Soundset', 0, 0, 1)
    local blip = AddBlipForCoord(data.coords)
    SetBlipSprite(blip, data.blip.blipid)
    SetBlipDisplay(blip, 4)
    SetBlipScale(blip, Config.BlipScale)
    SetBlipColour(blip, data.blip.blipcolor)
    SetBlipAsShortRange(blip, true)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentString(data.title .. " [#".. data.dispatchnumber .."]")
    EndTextCommandSetBlipName(blip)
    PulseBlip(blip)
    Wait(Config.RemoveBlipAfter)
    RemoveBlip(blip)
end 